//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.23 at 06:42:22 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/javaguys/webservices/getUserServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.javaguys.webservices.getUserServices;
