
package com.agimatec.publicinterfaces.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSReservationService", targetNamespace = "http://service.publicinterfaces.agimatec.com", wsdlLocation = "file:/D:/users/savarimuthu.s/git/javarepo/src/wsdl/WSReservationService.wsdl")
public class WSReservationService_Service
    extends Service
{

    private final static URL WSRESERVATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException WSRESERVATIONSERVICE_EXCEPTION;
    private final static QName WSRESERVATIONSERVICE_QNAME = new QName("http://service.publicinterfaces.agimatec.com", "WSReservationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/users/savarimuthu.s/git/javarepo/src/wsdl/WSReservationService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSRESERVATIONSERVICE_WSDL_LOCATION = url;
        WSRESERVATIONSERVICE_EXCEPTION = e;
    }

    public WSReservationService_Service() {
        super(__getWsdlLocation(), WSRESERVATIONSERVICE_QNAME);
    }

    public WSReservationService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSRESERVATIONSERVICE_QNAME, features);
    }

    public WSReservationService_Service(URL wsdlLocation) {
        super(wsdlLocation, WSRESERVATIONSERVICE_QNAME);
    }

    public WSReservationService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSRESERVATIONSERVICE_QNAME, features);
    }

    public WSReservationService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSReservationService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSReservationService
     */
    @WebEndpoint(name = "WSReservationServiceImplPort")
    public WSReservationService getWSReservationServiceImplPort() {
        return super.getPort(new QName("http://service.publicinterfaces.agimatec.com", "WSReservationServiceImplPort"), WSReservationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSReservationService
     */
    @WebEndpoint(name = "WSReservationServiceImplPort")
    public WSReservationService getWSReservationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.publicinterfaces.agimatec.com", "WSReservationServiceImplPort"), WSReservationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSRESERVATIONSERVICE_EXCEPTION!= null) {
            throw WSRESERVATIONSERVICE_EXCEPTION;
        }
        return WSRESERVATIONSERVICE_WSDL_LOCATION;
    }

}
